config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  get "pages", to: "pages#home"
  get "trigger_service", to: "pages#trigger_service"
  resources :items, only: [:update]
  post "/items/update-all", to: "items#update_all"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attempt.rb
class Attempt < ApplicationRecord

end

app/models/current_level.rb
class CurrentLevel < ApplicationRecord
  has_many :items
  has_one :success_chance
  has_many :materials
  validates :level, numericality: { only_integer: true, in: 0..19 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :current_level
  belongs_to :attempt
  has_many :materials
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :item
  belongs_to :current_level
end

app/models/success_chance.rb
class SuccessChance < ApplicationRecord
  belongs_to :current_level
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# app/controllers/application_controller.rb
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.order(:order)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

    @current_levels = []
    @items = []
    # materials hash of arrays: each entry is an array of materials for a specific item
    @materials = {}
    @mats = {
      silver: "https://i.imgur.com/sWFzPpF.png",
      gold: "https://i.imgur.com/bhEgr47.png",
      shards: "https://i.imgur.com/sjexkJA.png",
      oreha: "https://i.imgur.com/BcSu9Iv.png",
      destruction: "https://i.imgur.com/6zti2bC.png",
      leapstone: "https://i.imgur.com/wioa5ji.png",
      guardian: "https://i.imgur.com/JNFBDGK.png"
    }
    @matsid = ["sWFzPpF", "bhEgr47", "sjexkJA", "BcSu9Iv", "6zti2bC", "wioa5ji", "JNFBDGK"]

    @optionals = { 'solar grace': [24, 0.25], 'solar blessing': [12, 0.5], 'solar protection': [6, 1] }

    # {"item"=>{"helmet"=>"7", "shoulders"=>"3", "armour"=>"14", "pants"=>"2", "gloves"=>"12", "weapon"=>"12"}, "commit"=>"Save Item"}

    params[:item].each_key do |item|
      @item = Item.find_by(name: item)
      @current_level = CurrentLevel.find_by(level: params[:item][item])
      @item.update(current_level: @current_level)

      @items << @item
      @current_levels << @current_level
    end

    @items.each do |item|
      @materials[item.name] = item.materials.where(current_level: item.current_level)
    end

    @service = CalculationService.new(@items[1].current_level, @items[1])
    @success = @service.perform!
    Attempt.create!
    # # counter for the total attemps made on the session
    @total_attempt_counter = Attempt.all.count - 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/application/_active_item.html.erb
<div class="d-flex justify-content-center" data-active-target="honed">
  <div data-active-target="img" class="d-flex justify-content-center">
    <%# <h1 class="honing-item"></h1> %>
    <div>
      <h2 class="honing-level" data-active-target="level" data-computations-target="level" style="margin-top: 115px;"></h2>
    </div>
    <div class="gif" id="ghost" data-computations-target="win">
      <%= image_tag "success.gif" %>
    </div>
    <div class="gif" id="ghost" data-computations-target="fail">
      <%= image_tag "fail.gif" %>
    </div>
  </div>
</div>

app/views/application/_cards.html.erb
  <!--   <% @current_level.materials.each do |material| %>
      <div><%= image_tag "materials/#{material.name}.png" %></div>
    <% end %>
  </div>-->

<%# choose which material to display %>

<div class="cards" style="margin: 0 42px;">
  <div class="grid mt-5" data-active-target="cards" data-computations-target="cards" data-matsid="<%= @matsid %>">
  </div>
</div>

app/views/application/_counter.html.erb
<h3 style="text-align: center;">COUNTER</h3>
  <div class="col-2">
    <div class="attempts" id="mats" data-computations-target="materials">
      <% @materials = @materials["helmet"] %>
      <% @materials.each do |material| %>
        <div class="counter" data-amount="<%=material.amount%>" data-name="<%=material.name%>">
          <%= image_tag(@mats[material.name.to_sym], class:"mat-pic")%>
          <div class="notification-content" data-action="click->computations#hone" >
            <h5>0</h5>
          </div>
        </div>
      <% end %>
    </div>

    <h4 style="text-align: center;" class="mt-4 d-none">ATTEMPTS</h4>
    <div class="attempts d-none">
      <div class="d-flex justify-content-between w-100">
        <p>CURRENT</p>
        <p><small>9</small></p>
      </div>
      <div class="d-flex justify-content-between w-100">
        <p>TOTAL</p>
        <p><small><%= @total_attempt_counter %></small></p>
      </div>
    </div>
  </div>


<!-- mat_images = {shard: "https://imgur.com/sjexkJA", gold: "https://imgur.com/bECYx7J", silver: "https://imgur.com/sWFzPpF", oreha: "https://imgur.com/BcSu9Iv", leapstone: "https://imgur.com/wioa5ji", destruction: "https://imgur.com/6zti2bC", guardian: "https://imgur.com/JNFBDGK"}

mats"

image_tag (mat_images[mat.name.to_sym], class: "some bs class") -->

app/views/application/_hone.html.erb
<div data-current-level="<%= @service.current_level.level %>" data-computations-target="service">
  <div class="d-flex justify-content-center w-100 my-5" data-action="click->computations#hone">
    <h3 class="button-primary">HONE</h3>
  </div>
</div>

app/views/application/_item_list.html.erb
<div class="item-list">
  <h3 style="text-align: center;">GEAR</h3>
  <div class="items d-flex flex-column justify-content-between" >

    <div data-gear="<%= @items[0].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[0].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[0].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p>+<%= @items[0].current_level.level %></p>
    </div>

    <div data-gear="<%= @items[1].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[1].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[1].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p>+<%= @items[1].current_level.level %></p>
    </div>

    <div data-gear="<%= @items[2].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[2].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[2].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p >+<%= @items[2].current_level.level %></p>
    </div>

    <div data-gear="<%= @items[3].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[3].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[3].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p>+<%= @items[3].current_level.level %></p>
    </div>

    <div data-gear="<%= @items[4].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[4].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[4].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p >+<%= @items[4].current_level.level %></p>
    </div>

    <div data-gear="<%= @items[5].name %>" data-action="click->active#select click->computations#progressBar" data-active-target="gear" data-level="<%= @items[5].current_level.level %>" class="text-center">
      <%=image_tag("items/#{@items[5].name}.png", class:"item_pic rounded-circle border border-white", style:"width: 70px; height: 70px;")%>
      <p>+<%= @items[5].current_level.level %></p>
    </div>

  </div>
</div>

app/views/application/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= image_tag("LA_LOGO.png", class:"navbar-img") %>
    <h1 style="margin-top: 17px;">HONING SYMULATOR</h1>
  </div>
  <div class="navbar-links">
    <h4><%= link_to("SET ITEMS", root_path, class: "help-link") %></h4>
    <!--<div class="report-a-bug-link">
      <h4>REPORT A BUG</h4>
    </div>-->
  </div>
</div>

app/views/application/_optional_mats.html.erb
<div class="container-sliders mt-100" data-controller="slider" style="margin: 0 42px;">
  <% @optionals.each_with_index do |(optional_key, optional_value), index| %>
    <div class="solar-blessing-slider">
      <div style="d-flex align-items-end">
        <%=image_tag("materials/#{optional_key}.png", class:"material_icon")%>
        <div class="d-flex">
          <p data-slider-target="number" data-computations-target="number" id="<%= index %>">0</p>
          <p>/<%= optional_value[0] %></p>
        </div>
      </div>
      <div class="slider">
        <input type="range" min="0" max="<%= optional_value[0] %>" value="0" class="slider" id="<%= index %>" data-action="input->slider#update input->computations#slider" data-percentage="<%= optional_value[1] %>">
      </div>
      <p><%= optional_value[1] %>%</p>
    </div>
  <% end %>
</div>

<!--  <div class="solar-grace-slider">
    <div style="d-flex">
      <%=image_tag("materials/solar grace.png", class:"material_icon")%>
      <p>0/24</p>
    </div>
    <div class="slider">
      <input type="range" min="0" max="24" value="0" class="slider" id="myRange">
    </div>
    <p>%</p>
  </div>

  <div class="solar-blessing-slider">
    <div style="d-flex">
      <%=image_tag("materials/solar blessing.png", class:"material_icon")%>
      <p>0/12</p>
    </div>
    <div class="slider">
      <input type="range" min="0" max="12" value="0" class="slider" id="myRange">
    </div>
    <p>%</p>
  </div>

  <div class="solar-protection-slider">
    <div style="d-flex">
      <%=image_tag("materials/solar protection.png", class:"material_icon")%>
      <p>0/6</p>
    </div>
    <div class="slider">
      <input type="range" min="0" max="6" value="0" class="slider" id="myRange">
    </div>
    <p>%</p>
  </div>
    <% @optionals.each_with_index do |optional, index| %>
    <div class="solar-blessing-slider">
      <div style="d-flex">
        <%=image_tag("materials/solar blessing.png", class:"material_icon")%>
        <p data-slider-target="number" id="<%= index %>">0/12</p>
      </div>
      <div class="slider">
        <input type="range" min="0" max="12" value="0" class="slider" id="<%= index %>" data-action="input->slider#update">
      </div>
      <p>%</p>
    </div>
  <% end %>

app/views/application/_progress_bars.html.erb
<!-- <div class="w3-light-grey w3-xlarge" style="width:100%">
  <div class="w3-container w3-green d-flex justify-content-space-between" style="width:<%= @current_level.success_chance.base %>%">
    <h2><%= @current_level.success_chance.base %>%</h2>
    <h2>/</h2>
    <h2><%= @current_level.success_chance.max %>%</h2>
  </div>
</div>
<h1></h1>
<div class="w3-light-grey w3-xlarge mb-5 d-none" style="width:75%">
  <div class="w3-container w3-green" style="width:50%">50%</div>
  <h3 class="SliderText" id="protection">Bad luck protection %</h3>
</div> -->


<div class="progress d-flex rounded-pill d-none" style="height:40px; margin: 32px;" style="width:100%" data-active-target="progressbar">
  <div class="progress-bar bg-success d-flex progress-bar-striped progress-bar-animated bg-warning" role="progressbar" style="width:" aria-valuenow="" aria-valuemin="0" aria-valuemax="100" data-computations-target="progress">
    <h4 style="color:black; margin-top: 6px;" data-computations-target="number"></h4>
  </div>
</div>

app/views/items/index.html.erb
<div class="index-body">
  <div class="container-index-main">
    <div class="header">
      <h1 class="index-h1">HONE YOUR ITEMS</h1>
    </div>
    <div class="container-index">
      <div class="form">
        <div class="form-conatiner" style="text-align: -webkit-center">
          <div class="form-items">
            <%= simple_form_for(:item, url: pages_path, method: "get") do |f|%>
              <% @items.each do |item| %>
                <div class="item-container">
                  <%= image_tag("items/#{item.name}.png", class:"item-img") %>
                  <%= f.input "#{item.name}", :collection => 0..19, input_html: { min: '0', max: '19' }, default: 0 %>
                </div>
              <% end %>
            </div>
            <%= f.submit "Save items", class:"button-items" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container">

    <div class="item-container">
      <%# insert img here %>
      <h2>Weapon</h2>
      <%= simple_form_for(@item, url: root_path) do |f|%>
        <%= f.input :current_level, as: :numeric, input_html: { min: '1', max: '20' } %>
        <%= f.submit %>
      <% end %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag %>
    <title>Lost Ark Honing Symulator</title>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body style="color: white;">
  <%= render "navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5" data-controller="computations active">

  <!-- DIV FOR ITEM LIST (LEFT) -->
  <div class="container-left">
    <%= render "item_list" %>
  </div>

  <!-- DIV FOR ACTIVE ITEM / PROGRESS BARS / OPTIONALS / CARDS / HONE BTN (MIDDLE) -->
  <div class="container-middle">
    <%= render "active_item" %>
    <h1 data-computations-target="success" style="text-align: -webkit-center; padding: 2px 0; color: whitesmoke;
    text-shadow: 2px 2px 10px white;"></h1>
    <div class="wrap-middle">
      <%= render "progress_bars"%>
      <%= render "optional_mats" %>
      <%= render "cards" %>
      <%= render "hone" %>
    </div>
  </div>
  <!-- DIV FOR COUNTERS (RIGHT) -->
  <div class="container-right">
    <%= render "counter" %>
  </div>

</div> <!-- container -->

app/views/pages/old_home.html.erb
<div class="container mt-5" data-controller="honing">
  <%= link_to("Chose items", root_path) %>
  <div class="d-flex justify-content-center">
    <%=image_tag("items/pants.png", class:"selected_item")%>
  </div>

  <div class="row mt-5">
    <%= render "item_list" %>

    <div class="col-8 d-flex align-items-center" style="flex-direction: column;">
      <%= render "progress_bars" %>
      <%= render "optional_mats" %>
      <%= render "cards" %>
    </div>
    <%= render "counter" %>
   <%# HERE %>
</div>

<%= render "hone" %>

app/views/pages/separatecomponents.html.erb
<div class="container">
<%= @success %>

<div class="header">
  <h1>Lost Ark Honing Simulator</h1>
</div>


<div class="slidecontainer">
  <input type="range" min="1" max="100" value="50" class="slider" id="myRange">
</div>

<div class="w3-light-grey w3-xlarge" style="width:50%">
  <div class="w3-container w3-green" style="width:50%">50%</div>
  <h3 class="SliderText"> Success chance / max success chance</h3>
</div>

<br><br>

<div class="w3-light-grey w3-xlarge" style="width:50%">
  <div class="w3-container w3-green" style="width:50%">50%</div>
  <h3 class="SliderText" id="protection"> Bad luck protection %</h3>
</div>

<div class="counter">
  <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large" />
  <div class="notification-content">
    <h2>100/1000</h2>
  </div>
</div>

<div class="cards w-50">
  <div class="card-category" style="background-color:white; color:black;">
    Material 1 <br>
    <img class="avatar-bordered" alt="avatar-bordered" src="https://kitt.lewagon.com/placeholder/users/sarahlafer" /> <br>
    1000/5000 <br>
  </div>
</div>
<img class="avatar-square" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />

</div>
</div>